export const PLUS = '+'
export const GENERAL_INFO = 'General Info'
export const ADDRESS = 'Address'
export const NAME = 'Name'
export const YOUR_IMAGE = 'Your Image'
export const METADATA = 'Metadata'
export const PRICE = 'Price'
export const MINT = 'Mint'
